apiVersion: 1.0.0
kind: Plugin
metadata:
  name: RethinkDB Storage
  description: RethinkDB storage plugin for Reekoh IoT Platform.
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - storage
    - rethink
    - rethinkdb
    
  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      host:
        label: Host
        type: String
        required: true
        help: "Host for the RethinkDB Database Server."
        maxLength: 1000
      port:
        label: Port
        type: Number
        required: true
        min: 1
        max: 56353
        help: "Port for the RethinkDB Database Server."
      database:
        label: Database Name
        type: String
        required: true
        help: "Database Name where data will be sent to."
        maxLength: 1000
      table:
        label: Table Name
        type: String
        required: true
        help: "Table Name where the data will be inserted to."
        maxLength: 1000
      user:
        label: User
        type: String
        required: false
        maxLength: 1000
        help: "(Optional) Username to use for authentication with the RethinkDB Database."
      password:
        label: Auth Key/Password
        type: Password
        maxLength: 1000
        required: true
        help: "(Optional) Auth Key/Password to use for authentication with the RethinkDB Database."
